source_path: ./
report_path: reports
safelist_path: .annotation_safe_list.yml
coverage_target: 50.0
annotations:
  events:
    - ".. event_type:":
    - ".. event_name:":
    - ".. event_description:":
    - ".. event_data:":
extensions:
    python:
        - py
rst_template: doc.rst.j2
